openapi: 3.0.3
info:
  title: Fi-Zen Analytics & Reporting API
  description: Analytics, reporting and business intelligence APIs
  version: 1.0.0

servers:
  - url: https://api.fi.money/v1/analytics

paths:
  /user-metrics:
    get:
      summary: Get User Analytics
      description: Retrieve user engagement and usage metrics
      tags:
        - User Analytics
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
          example: "fi_user_123456"
        - name: period
          in: query
          schema:
            type: string
            enum: [7d, 30d, 90d, 1y]
            default: 30d
      responses:
        '200':
          description: User metrics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        example: "fi_user_123456"
                      period:
                        type: string
                        example: "30d"
                      metrics:
                        type: object
                        properties:
                          calculationsPerformed:
                            type: number
                            example: 15
                          professionalToolsUsed:
                            type: number
                            example: 8
                          averageInflationRate:
                            type: number
                            example: 11.2
                          engagementScore:
                            type: number
                            description: User engagement score (0-100)
                            example: 78
                          featureUsage:
                            type: object
                            properties:
                              salaryNegotiation:
                                type: number
                                example: 3
                              cityComparison:
                                type: number
                                example: 2
                              peerBenchmarking:
                                type: number
                                example: 5

  /business-intelligence:
    get:
      summary: Get Business Intelligence Data
      description: Aggregate analytics for business insights
      tags:
        - Business Intelligence
      parameters:
        - name: metric
          in: query
          required: true
          schema:
            type: string
            enum: [user_growth, feature_adoption, inflation_trends, revenue_metrics]
        - name: period
          in: query
          schema:
            type: string
            default: 30d
      responses:
        '200':
          description: BI data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      metric:
                        type: string
                        example: "user_growth"
                      aggregatedData:
                        type: object
                        properties:
                          totalUsers:
                            type: number
                            example: 25847
                          activeUsers:
                            type: number
                            example: 18234
                          newUsers:
                            type: number
                            example: 2156
                          retentionRate:
                            type: number
                            example: 68.5
                          averageInflationRate:
                            type: number
                            example: 10.8
                          topCities:
                            type: array
                            items:
                              type: object
                              properties:
                                city:
                                  type: string
                                  example: "Mumbai"
                                userCount:
                                  type: number
                                  example: 8234
                                avgInflation:
                                  type: number
                                  example: 11.8

  /cross-sell-analytics:
    get:
      summary: Get Cross-sell Performance
      description: Analytics for Fi product cross-selling
      tags:
        - Revenue Analytics
      responses:
        '200':
          description: Cross-sell analytics retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      conversionRates:
                        type: object
                        properties:
                          fiMutualFunds:
                            type: number
                            example: 12.5
                          fiSavingsPlus:
                            type: number
                            example: 8.3
                          premiumFeatures:
                            type: number
                            example: 5.2
                      revenueGenerated:
                        type: object
                        properties:
                          totalRevenue:
                            type: number
                            example: 2500000
                          averageRevenuePerUser:
                            type: number
                            example: 125

components:
  securitySchemes:
    FiAuth:
      type: http
      scheme: bearer

security:
  - FiAuth: []
